# Generated by Django 4.1.4 on 2022-12-30 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Message', models.CharField(max_length=160)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone', models.IntegerField()),
                ('Country', models.CharField(choices=[('USA', 'USA'), ('INDIA', 'INDIA')], max_length=5)),
                ('Schedule_date', models.DateField(blank=True, null=True)),
                ('Schedule_time', models.TimeField(blank=True, null=True)),
            ],
        ),
    ]
