# Generated by Django 4.1.4 on 2022-12-30 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailmessaging', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='Schedule_time',
        ),
        migrations.AlterField(
            model_name='messages',
            name='Schedule_date',
            field=models.DateField(),
        ),
    ]
