# Generated by Django 4.1.4 on 2022-12-30 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailmessaging', '0002_remove_messages_schedule_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='Phone',
            field=models.IntegerField(null=True),
        ),
    ]
