# Generated by Django 4.1.4 on 2022-12-30 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailmessaging', '0003_alter_messages_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='Schedule_date',
            field=models.DateField(null=True),
        ),
    ]
