# Generated by Django 4.1.4 on 2022-12-30 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailmessaging', '0004_alter_messages_schedule_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='Phone',
            field=models.IntegerField(default=123),
        ),
        migrations.AlterField(
            model_name='messages',
            name='Schedule_date',
            field=models.CharField(default='hii', max_length=20),
        ),
    ]
