# Generated by Django 4.1.4 on 2022-12-31 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailmessaging', '0006_alter_messages_phone_alter_messages_schedule_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='validatorlog',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
