# Generated by Django 4.1.4 on 2022-12-31 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailmessaging', '0008_alter_messages_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='Country',
            field=models.CharField(max_length=20),
        ),
    ]
